---
- name: Install dhcp on Ubuntu
  apt:
    name: dhcp
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install dhcp on CentOS
  dnf:
    name: dhcp
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"
