- name: Install vsftpd Ubuntu 
  apt:
    name:
      - vsftpd 
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install vsftpd CentOS
  dnf:
    name:
      - vsftpd
    state: latest
    update_cache: yes
  when: ansile_distribution == "CentOS"
